# Provider specific overrides for the aws provider
#
# You can add overrides for other providers by creating a <provider>.yml file in
# this directory where <provider> is the provider name.
#
# Overrides in this file should NOT be scoped under a "providers ->
# <provider>" hash like they need to be in atmos.yml
#
region: us-east-1
auth:
  session_duration: 3600
  assume_role_name: "#{atmos_env}-admin"
  bootstrap_assume_role_name: "OrganizationAccountAccessRole"
backend:
  type: s3
  bucket: "#{global_name_prefix}terraform-state"
  key: "terraform.tfstate"
  region: "#{region}"
  encrypt: true
  dynamodb_table: "#{global_name_prefix}atmos-terraform-lock"
secret:
  type: s3
  bucket: "#{global_name_prefix}secrets"
  region: "#{region}"
  encrypt: true
